name: build

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows for the workflow to be manually started through the GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QT6_VERSION: '6.6.0'
    steps:
      - name: Check Contexts and Secrets
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.workspace = ${{ github.workspace }}"
          echo "[Secrets]"
          echo "secrets.GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Testing
        run: |
          # apt list pkg-config
          # apt list libpango1.0-dev
          # apt list libcogl-pango-dev
          # apt list libjpeg-dev
          apt list llvm-14
          apt list clang-14
          apt list libclang-14-dev

      # # https://wiki.qt.io/Building_Qt_6_from_Git
      # - name: Install the Prerequisites
      #   run: |
      #     sudo apt update
      #     sudo apt install \
      #       cmake \
      #       python3 \
      #       python3-pip \
      #       ninja-build \
      #       bison \
      #       flex \
      #       perl \
      #       gperf \
      #       libnss3-dev \
      #       libdbus-1-dev \
      #       libclang-15-dev \
      #       libgl-dev \
      #       libegl-dev \
      #       libfontconfig1-dev \
      #       libinput-dev
      #     sudo apt install libpango1.0-dev
      #     sudo apt install libcogl-pango-dev
      #     sudo apt install libjpeg-dev

      # - name: Install the Prerequisites (html5lib)
      #   run: |
      #     pip install html5lib

      # - name: Install the Prerequisites (NodeJS 14)
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 14

      # - name: Check the Installation
      #   run: |
      #     which cmake && cmake --version
      #     echo "----------------------------------------"
      #     which python3 && python3 --version
      #     echo "----------------------------------------"
      #     which ninja && ninja --version
      #     echo "----------------------------------------"
      #     which node && node --version
      #     echo "----------------------------------------"
      #     which bison && bison --version
      #     echo "----------------------------------------"
      #     which flex && flex --version
      #     echo "----------------------------------------"
      #     which perl && perl --version
      #     echo "----------------------------------------"
      #     which gperf && gperf --version

      # - name: Prepare the Qt6 Sources
      #   run: |
      #     curl -L https://download.qt.io/archive/qt/6.6/${{ env.QT6_VERSION }}/single/qt-everywhere-src-${{ env.QT6_VERSION }}.tar.xz -o qt-everywhere-src-${{ env.QT6_VERSION }}.tar.xz
      #     tar -xf qt-everywhere-src-${{ env.QT6_VERSION }}.tar.xz
      #     mv qt-everywhere-src-${{ env.QT6_VERSION }} qt6

      # - name: Configure the Qt6 Project
      #   run: |
      #     cd qt6
      #     mkdir build && cd build
      #     ../configure \
      #       -developer-build 
      #       # -prefix ${{ github.workspace }}/html

      # - name: Build the Qt6 Project with the 'html_docs' Target
      #   run: |
      #     cd qt6
      #     cd build
      #     cmake --build . --target html_docs

      # # - name: Install the Qt6 Project
      # #   run: |
      # #     cd qt6
      # #     cd build
      # #     cmake --install .

      # - name: Deploy to 'gh-pages' branch
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: gh-pages
      #     folder: ./qt6/build/qtbase/doc
      #     target-folder: .
      #     clean: false